### ISSUE TITLE
no logs in Console

### ISSUE THREAD

**Issue by zephyo** [Phylliida/P2P.NET#1]
hi, this looks really useful, but a connection doesn't seem to get established. I opened a webgl build of the demo scene, code untouched, but console didn't show id/connection/any logs. I tried both the bean and nameless-scrubland wsurls. PS the js console gave me these errors;
![screen shot 2017-10-14 at 12 06 02 pm](https://user-images.githubusercontent.com/22963510/31578542-1d805932-b0d8-11e7-8983-cc7562b7be9c.png)

**Comment by Phylliida** [comment]
Hmm, so unfortunately the issue is that WebGL doesn't allow multiple threads (and my code is written in a multithreaded way). So, ironically, the major platform that can't run P2P.NET is webgl. One way to get around this is to use a javascript plugin (you can only do this for WebGL) [this](https://forum.unity.com/threads/unitypeerjs-simple-webrtc-support-for-unity-webgl.310166/) might work I'm not sure

**Comment by zephyo** [comment]
thanks for the fast reply, I'll check it out; might just stick to standalone since WebGL has so many issues
